review_tree = {
    "start": [
        "I",
        "We",
        "My family",
        "Our friends",
        "A group of us",
        "My colleagues and I",
        "My partner and I",
        "The kids and I",
        "Our team",
        "My buddies and I",
        "My roommates",
        "My neighbors and I",
        "My classmates and I",
        "Our sports team",
        "The whole gang",
        "The entire office",
        "My best friend and I",
        "My siblings and I",
        "My spouse and I",
        "My partner and friends",
        "My book club",
        "My parents and I",
        "My grandparents",
        "My aunts and uncles",
        "My cousins",
        "My friends and I",
        "My extended family",
        "Our hiking group",
        "Our running club",
        "My soccer team",
        "My basketball team",
        "My work team",
        "Our project group",
        "My study group",
        "Our gaming group",
        "Our travel group",
        "My band",
    ],
    "I": [
        "went",
        "had a great time",
        "loved",
        "enjoyed our visit",
        "visited",
        "experienced",
        "had an amazing dinner",
        "checked out",
        "tried",
        "decided to go",
        "spent the evening",
        "had a lunch",
        "decided to have a meal",
        "went for a quick bite",
        "decided to have a casual dinner",
        "planned a visit",
        "went for a celebratory meal",
        "chose to dine",
        "decided to hang out",
    ],
    "We": [
        "went",
        "had a fantastic experience",
        "enjoyed",
        "loved our time",
        "checked out",
        "decided to try",
        "had an incredible lunch",
        "experienced",
        "tried",
        "spent our evening",
        "had a fun time",
        "had a great night",
        "chose to dine",
        "went for a casual meal",
        "planned a dinner",
        "went for a celebration",
        "decided to visit",
        "decided to check out",
    ],
    "My family": [
        "visited",
        "had a wonderful time",
        "loved",
        "enjoyed our outing",
        "went",
        "had an amazing day",
        "checked out",
        "tried",
        "decided to go",
        "spent our evening",
        "had a lunch",
        "had a great dinner",
        "had a fantastic time",
        "planned a visit",
        "went for a meal",
        "decided to dine",
        "decided to have a fun day",
        "decided to enjoy a family meal",
    ],
    "Our friends": [
        "went",
        "had a great day",
        "enjoyed",
        "had a blast",
        "checked out",
        "experienced",
        "decided to try",
        "had a fun night",
        "tried",
        "spent our evening",
        "chose to dine",
        "had a great time",
        "had a fun day",
        "went for a casual meal",
        "decided to visit",
        "planned a dinner",
        "went for a night out",
        "decided to hang out",
    ],
    "A group of us": [
        "went",
        "had a fun evening",
        "enjoyed our visit",
        "checked out",
        "loved",
        "tried out",
        "visited",
        "spent the evening",
        "had a blast",
        "decided to go",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a night out",
        "decided to have a meal",
        "went for a casual dinner",
        "spent the day",
        "decided to check out",
    ],
    "My colleagues and I": [
        "went",
        "had a team outing",
        "enjoyed",
        "loved our visit",
        "had a fantastic lunch",
        "checked out",
        "decided to try",
        "experienced",
        "had a great time",
        "spent our evening",
        "chose to dine",
        "tried",
        "spent a fun time",
        "planned a team dinner",
        "decided to have a casual meal",
        "went for a work celebration",
        "decided to visit",
        "spent a fantastic day",
    ],
    "My partner and I": [
        "went",
        "had a date night",
        "loved our evening",
        "enjoyed our dinner",
        "visited",
        "tried",
        "checked out",
        "had a fantastic time",
        "spent our night",
        "decided to go",
        "had a great time",
        "chose to dine",
        "planned a romantic dinner",
        "went for a casual meal",
        "decided to visit",
        "went for a celebration",
        "decided to enjoy a night out",
        "spent a wonderful evening",
    ],
    "The kids and I": [
        "went",
        "had a fun day",
        "loved",
        "enjoyed our visit",
        "checked out",
        "tried",
        "visited",
        "had a blast",
        "spent the day",
        "decided to go",
        "had a great time",
        "spent our evening",
        "planned a fun outing",
        "decided to have a meal",
        "went for a casual dinner",
        "went for a day out",
        "decided to visit",
        "had a fantastic time",
    ],
    "Our team": [
        "went",
        "had a great outing",
        "enjoyed",
        "loved our time",
        "checked out",
        "decided to try",
        "experienced",
        "tried",
        "spent our evening",
        "had a fantastic time",
        "had a great night",
        "chose to dine",
        "spent the evening",
        "planned a team dinner",
        "went for a casual meal",
        "decided to visit",
        "spent a fun day",
        "decided to have a celebration",
    ],
    "My buddies and I": [
        "went",
        "had a guys' night",
        "enjoyed",
        "loved our visit",
        "had a fantastic dinner",
        "checked out",
        "decided to try",
        "experienced",
        "had a great time",
        "spent our evening",
        "had a fun time",
        "tried",
        "chose to dine",
        "planned a night out",
        "decided to visit",
        "went for a casual meal",
        "decided to have a meal",
        "spent a fun evening",
    ],
    "My roommates": [
        "went",
        "had a fun evening",
        "enjoyed our visit",
        "checked out",
        "loved",
        "tried out",
        "visited",
        "spent the evening",
        "had a blast",
        "decided to go",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a casual dinner",
        "went for a meal",
        "decided to explore",
        "chose to visit",
        "spent a fun day",
        "decided to hang out",
    ],
    "My neighbors and I": [
        "went",
        "had a great time",
        "enjoyed",
        "loved our visit",
        "checked out",
        "decided to try",
        "experienced",
        "tried",
        "spent the evening",
        "had a fantastic time",
        "had a fun night",
        "chose to dine",
        "planned a neighborhood outing",
        "went for a casual meal",
        "decided to visit",
        "spent a wonderful evening",
        "decided to have a dinner",
        "went for a meal",
    ],
    "My classmates and I": [
        "went",
        "had a study break",
        "enjoyed",
        "loved our visit",
        "checked out",
        "decided to try",
        "experienced",
        "tried",
        "spent our evening",
        "had a great time",
        "had a fun time",
        "chose to dine",
        "planned a study break",
        "went for a casual meal",
        "decided to visit",
        "spent a fantastic evening",
        "decided to hang out",
        "went for a night out",
    ],
    "Our sports team": [
        "went",
        "had a team celebration",
        "enjoyed",
        "loved our time",
        "checked out",
        "decided to try",
        "experienced",
        "tried",
        "spent our evening",
        "had a fantastic time",
        "had a great night",
        "chose to dine",
        "spent the evening",
        "planned a team outing",
        "went for a meal",
        "decided to explore",
        "chose to visit",
        "spent a fun day",
        "decided to have a celebration",
    ],
    "The whole gang": [
        "went",
        "had a fun evening",
        "enjoyed our visit",
        "checked out",
        "loved",
        "tried out",
        "visited",
        "spent the evening",
        "had a blast",
        "decided to go",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a night out",
        "decided to have a meal",
        "went for a casual dinner",
        "spent a fantastic evening",
        "decided to visit",
    ],
    "The entire office": [
        "went",
        "had an office outing",
        "enjoyed",
        "loved our visit",
        "had a team lunch",
        "checked out",
        "decided to try",
        "experienced",
        "had a great time",
        "spent our evening",
        "chose to dine",
        "tried",
        "spent a fun time",
        "planned a team dinner",
        "went for a casual meal",
        "decided to visit",
        "decided to have a celebration",
    ],
    "My best friend and I": [
        "went",
        "had a great time",
        "loved",
        "enjoyed our visit",
        "visited",
        "experienced",
        "had an amazing dinner",
        "checked out",
        "tried",
        "decided to go",
        "spent the evening",
        "had a lunch",
        "decided to have a meal",
        "went for a casual dinner",
        "planned a visit",
        "decided to explore",
        "spent a fun evening",
        "decided to hang out",
        "chose to dine",
    ],
    "My siblings and I": [
        "went",
        "enjoyed",
        "loved our visit",
        "had a family dinner",
        "checked out",
        "decided to try",
        "experienced",
        "had a great time",
        "spent our evening",
        "chose to dine",
        "tried",
        "spent a fun time",
        "planned a family meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fantastic evening",
        "decided to have a meal",
    ],
    "My spouse and I": [
        "went",
        "had a wonderful evening",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a romantic dinner",
        "went for a casual meal",
        "decided to visit",
        "spent a lovely evening",
        "decided to have a meal",
    ],
    "My partner and friends": [
        "went",
        "had a fantastic time",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a great dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a night out",
        "went for a casual meal",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "My book club": [
        "went",
        "had a book discussion night",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a great dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a book discussion",
        "went for a casual meal",
        "decided to visit",
        "spent a fantastic evening",
        "decided to have a meal",
    ],
    "My parents and I": [
        "went",
        "had a family outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a family meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "My grandparents": [
        "went",
        "had a lovely outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a lovely dinner",
        "went for a casual meal",
        "decided to visit",
        "spent a wonderful evening",
        "decided to have a meal",
    ],
    "My aunts and uncles, My extended family": [
        "went",
        "had a family outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a great dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a family meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a wonderful evening",
        "decided to have a meal",
    ],
    "My cousins": [
        "went",
        "had a fun outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a casual dinner",
        "went for a meal",
        "decided to visit",
        "spent a wonderful evening",
        "decided to have a meal",
    ],
    "My friends and I": [
        "went",
        "had a great time",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a night out",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "Our hiking group": [
        "went",
        "had a post-hike meal",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fantastic evening",
        "decided to have a meal",
    ],
    "Our running club": [
        "went",
        "had a post-run meal",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fantastic evening",
        "decided to have a meal",
    ],
    "My soccer team, My basketball team": [
        "went",
        "had a post-game meal",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a team meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "My work team": [
        "went",
        "had a work outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a team meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "Our project group": [
        "went",
        "had a project celebration",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a celebration meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "My study group": [
        "went",
        "had a study break",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a great dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a study break meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "Our gaming group": [
        "went",
        "had a gaming night out",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a night out",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "Our travel group": [
        "went",
        "had a great outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a great dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "My band": [
        "went",
        "had a band outing",
        "enjoyed our visit",
        "loved",
        "checked out",
        "decided to try",
        "visited",
        "experienced",
        "had a fantastic dinner",
        "spent the evening",
        "had a great time",
        "tried",
        "chose to dine",
        "planned a meal",
        "went for a casual dinner",
        "decided to visit",
        "spent a fun evening",
        "decided to have a meal",
    ],
    "went": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a great time",
        "and enjoyed a wonderful meal",
        "and were pleasantly surprised by the atmosphere",
        "and loved the food",
        "and had a fantastic experience",
        "and were impressed with the service",
        "and had an amazing dinner",
        "and tried the wings",
        "and loved the drinks",
    ],
    "had a great time": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and will definitely be back",
        "and highly recommend it",
        "and can't wait to return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "loved": [
        "the food at Buffalo Wild Wings",
        "the atmosphere at BWW",
        "our experience at B-Dubs",
        "the wings at the local Buffalo Wild Wings",
        "the service at our favorite wing spot",
        "everything about the Buffalo Wild Wings in town",
        "the drinks at the nearby BWW",
        "the vibe at our go-to B-Dubs",
        "the menu at the Buffalo Wild Wings",
        "the specials at the popular BWW nearby",
    ],
    "enjoyed our visit": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a fantastic time",
        "and can't wait to go back",
        "and were delighted with the experience",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a study break, enjoyed our dinner": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic time",
        "and can't wait to go back",
        "and were delighted with the experience",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a post-run meal, loved our time, had a post-hike meal, went for a casual meal, had a fantastic lunch, decided to enjoy a family meal, spent our night, had a team lunch, went for a quick bite": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and can't wait to return",
        "and had an amazing experience",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "planned a dinner, went for a casual dinner": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and can't wait to return",
        "and had an amazing experience",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a fantastic experience, chose to dine": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and will be returning soon",
        "and highly recommend it to everyone",
        "and thoroughly enjoyed every moment",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "enjoyed": [
        "the wings at Buffalo Wild Wings",
        "the atmosphere at BWW",
        "our visit to B-Dubs",
        "the drinks at the local Buffalo Wild Wings",
        "the variety at our favorite wing spot",
        "the vibe at the Buffalo Wild Wings in town",
        "the service at the nearby BWW",
        "the menu at our go-to B-Dubs",
        "the desserts at the Buffalo Wild Wings",
        "the appetizers at the popular BWW nearby",
        "and will definitely be back",
        "and were very satisfied",
        "and had a wonderful time",
        "and loved the food",
        "and had a fantastic experience",
        "and were impressed with the service",
        "and had a great meal",
        "and enjoyed the drinks",
        "and had a memorable experience",
    ],
    "visited, chose to visit, decided to visit": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a great time",
        "and were pleasantly surprised",
        "and thoroughly enjoyed it",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a wonderful time, spent the evening": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and will definitely return",
        "and highly recommend it",
        "and enjoyed every moment",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "enjoyed our outing": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a blast",
        "and can't wait to go back",
        "and had an amazing time",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a great day": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic experience",
        "and will definitely return",
        "and recommend it highly",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a blast": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and can't wait to go back",
        "and had a wonderful time",
        "and thoroughly enjoyed ourselves",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "checked out": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a great time",
        "and were very impressed",
        "and enjoyed our visit",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "experienced": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a fantastic time",
        "and were very satisfied",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "decided to try": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
    ],
    "had an amazing dinner": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and can't wait to go back",
        "and were very satisfied",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had an incredible lunch": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and were very impressed",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a fun night, had a guys' night": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic time",
        "and thoroughly enjoyed ourselves",
        "and can't wait to go back",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "tried out": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a great time",
        "and thoroughly enjoyed it",
        "and highly recommend it",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "tried": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a wonderful time",
        "and were very impressed",
        "and can't wait to go back",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a team outing, planned a team outing": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic time",
        "and thoroughly enjoyed ourselves",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a date night": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and can't wait to return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a fun day": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic experience",
        "and thoroughly enjoyed ourselves",
        "and highly recommend it",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "had a great outing": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "and had a great time": [
        "The food was amazing, especially the wings.",
        "The service was top-notch and very friendly.",
        "We loved the atmosphere and the sports theme.",
        "The variety on the menu was impressive.",
        "The drinks were fantastic and well-made.",
        "The vibe was lively and perfect for a fun night.",
        "We enjoyed watching the game while eating.",
        "The dessert options were a delightful surprise.",
        "We were impressed with the speed of service.",
        "The place was clean and well-maintained.",
        "and the ambiance was great.",
        "and the prices were reasonable.",
        "and the portions were generous.",
        "and the staff was friendly.",
        "and the location was convenient.",
        "and the overall experience was excellent.",
        "and the specials were a real treat.",
        "and the presentation of the food was appealing.",
        "and we had a memorable time.",
    ],
    "and enjoyed a wonderful meal": [
        "The wings were perfectly cooked and flavorful.",
        "The appetizers were a great start to our meal.",
        "The main courses were delicious and satisfying.",
        "The sauces available were a real highlight.",
        "The portions were generous and filling.",
        "The kids loved their meals and the fun atmosphere.",
        "We appreciated the vegetarian options available.",
        "The special deals made it even better.",
        "The presentation of the food was very appealing.",
        "The overall experience was fantastic.",
        "and the desserts were amazing.",
        "and the drinks were spot on.",
        "and the atmosphere was enjoyable.",
        "and the service was excellent.",
        "and the variety was impressive.",
        "and the quality was top-notch.",
        "and the staff was attentive.",
        "and the ambiance was welcoming.",
        "and we can't wait to return.",
    ],
    "and were pleasantly surprised by the atmosphere": [
        "It was lively but not too loud.",
        "The decor was perfect for a sports bar.",
        "The seating was comfortable and spacious.",
        "The lighting was just right, not too bright.",
        "The ambiance was welcoming and relaxed.",
        "It was a great place to hang out with friends.",
        "The music selection added to the fun.",
        "The place had a nice mix of people.",
        "It felt like a community gathering spot.",
        "We felt right at home there.",
        "and the vibe was great.",
        "and the setting was perfect.",
        "and the atmosphere was inviting.",
        "and the ambiance was perfect.",
        "and the environment was clean.",
        "and the overall feel was nice.",
        "and the location was convenient.",
        "and the decor was tasteful.",
        "and the place was well-maintained.",
    ],
    "and will definitely be back": [
        "We can't wait to try more items on the menu.",
        "It's now one of our favorite spots.",
        "We're already planning our next visit.",
        "This will be a regular hangout for us.",
        "We highly recommend it to others.",
        "The overall experience was excellent.",
        "The staff made us feel very welcome.",
        "The quality of the food was outstanding.",
        "The service was consistently good.",
        "We had a memorable time there.",
        "and we loved every minute.",
        "and the experience was fantastic.",
        "and we had a great time.",
        "and the food was delicious.",
        "and the drinks were amazing.",
        "and the service was top-notch.",
        "and the ambiance was perfect.",
        "and the location was ideal.",
        "and the prices were reasonable.",
    ],
    "and can't wait to return": [
        "The wings were just that good.",
        "The whole experience was fantastic.",
        "We felt very welcomed and comfortable.",
        "The food was consistently excellent.",
        "The service was impeccable.",
        "The place has a great vibe.",
        "It's a great spot for watching sports.",
        "We enjoyed everything about it.",
        "The variety on the menu was great.",
        "We left feeling very satisfied.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the staff was friendly.",
        "and the atmosphere was lively.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
        "and the overall experience was wonderful.",
    ],
    "and will be coming back for more": [
        "The flavors were incredible.",
        "We loved the creativity of the dishes.",
        "The atmosphere was perfect.",
        "The service was quick and efficient.",
        "The prices were very reasonable.",
        "The staff was friendly and attentive.",
        "The place was very clean and tidy.",
        "We had a great overall experience.",
        "It's a perfect place for casual dining.",
        "We had a blast and loved every minute.",
        "and the wings were delicious.",
        "and the drinks were amazing.",
        "and the desserts were tasty.",
        "and the appetizers were great.",
        "and the service was top-notch.",
        "and the atmosphere was inviting.",
        "and the location was convenient.",
        "and the prices were fair.",
        "and the overall experience was excellent.",
    ],
    "and recommend it to everyone": [
        "The food was top-notch.",
        "The service was excellent.",
        "The atmosphere was lively.",
        "The drinks were amazing.",
        "The place was clean and well-kept.",
        "The menu was diverse and interesting.",
        "The prices were affordable.",
        "The location was great.",
        "The overall vibe was fantastic.",
        "We had a wonderful time there.",
        "and the wings were delicious.",
        "and the drinks were spot on.",
        "and the desserts were tasty.",
        "and the appetizers were great.",
        "and the service was top-notch.",
        "and the atmosphere was inviting.",
        "and the location was convenient.",
        "and the prices were fair.",
        "and the overall experience was wonderful.",
    ],
    "and were impressed with the variety": [
        "There was something for everyone.",
        "The menu had lots of options.",
        "The specials were unique and tasty.",
        "The drink selection was great.",
        "The appetizers were very good.",
        "The desserts were a nice touch.",
        "The portions were generous.",
        "The presentation was appealing.",
        "The flavors were amazing.",
        "The quality was consistent.",
        "and the wings were delicious.",
        "and the drinks were fantastic.",
        "and the desserts were great.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was lively.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and had a fantastic time": [
        "The food was delicious.",
        "The service was excellent.",
        "The atmosphere was great.",
        "The drinks were perfect.",
        "The place was clean and tidy.",
        "The menu was varied.",
        "The staff was friendly.",
        "The prices were reasonable.",
        "The location was convenient.",
        "The overall experience was excellent.",
        "and the wings were great.",
        "and the drinks were fantastic.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was top-notch.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was ideal.",
        "and the prices were fair.",
    ],
    "and were delighted with the experience": [
        "The wings were excellent.",
        "The appetizers were tasty.",
        "The main courses were delicious.",
        "The sauces were flavorful.",
        "The portions were filling.",
        "The desserts were delicious.",
        "The drinks were well-made.",
        "The service was great.",
        "The atmosphere was perfect.",
        "The place was very clean.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were tasty.",
        "and the appetizers were delicious.",
        "and the service was top-notch.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and will be returning soon": [
        "The food was outstanding.",
        "The service was impeccable.",
        "The atmosphere was inviting.",
        "The drinks were fantastic.",
        "The place was clean.",
        "The menu was diverse.",
        "The staff was friendly.",
        "The prices were fair.",
        "The location was ideal.",
        "The overall experience was great.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and thoroughly enjoyed every moment": [
        "The wings were fantastic.",
        "The appetizers were delightful.",
        "The main courses were superb.",
        "The sauces were perfect.",
        "The portions were huge.",
        "The desserts were incredible.",
        "The drinks were spot on.",
        "The service was wonderful.",
        "The atmosphere was perfect.",
        "The place was immaculate.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and highly recommend it to everyone": [
        "The food was exceptional.",
        "The service was wonderful.",
        "The atmosphere was lively.",
        "The drinks were great.",
        "The place was clean.",
        "The menu was varied.",
        "The staff was friendly.",
        "The prices were fair.",
        "The location was convenient.",
        "The overall experience was excellent.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and thoroughly enjoyed it": [
        "The wings were great.",
        "The appetizers were good.",
        "The main courses were tasty.",
        "The sauces were delicious.",
        "The portions were ample.",
        "The desserts were yummy.",
        "The drinks were nice.",
        "The service was good.",
        "The atmosphere was pleasant.",
        "The place was neat.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and will definitely return": [
        "The food was very good.",
        "The service was friendly.",
        "The atmosphere was fun.",
        "The drinks were nice.",
        "The place was tidy.",
        "The menu was varied.",
        "The staff was helpful.",
        "The prices were reasonable.",
        "The location was convenient.",
        "The overall experience was pleasant.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and had a wonderful time": [
        "The wings were excellent.",
        "The appetizers were nice.",
        "The main courses were good.",
        "The sauces were flavorful.",
        "The portions were filling.",
        "The desserts were tasty.",
        "The drinks were well-made.",
        "The service was friendly.",
        "The atmosphere was fun.",
        "The place was clean.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and highly recommend it": [
        "The food was delicious.",
        "The service was friendly.",
        "The atmosphere was lively.",
        "The drinks were great.",
        "The place was tidy.",
        "The menu was varied.",
        "The staff was helpful.",
        "The prices were fair.",
        "The location was convenient.",
        "The overall experience was good.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and had an amazing experience": [
        "The wings were outstanding.",
        "The appetizers were good.",
        "The main courses were tasty.",
        "The sauces were delicious.",
        "The portions were ample.",
        "The desserts were yummy.",
        "The drinks were nice.",
        "The service was good.",
        "The atmosphere was pleasant.",
        "The place was neat.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and were very satisfied": [
        "The wings were delicious.",
        "The appetizers were good.",
        "The main courses were tasty.",
        "The sauces were flavorful.",
        "The portions were generous.",
        "The desserts were nice.",
        "The drinks were well-made.",
        "The service was friendly.",
        "The atmosphere was lively.",
        "The place was clean.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and can't wait to go back": [
        "The wings were great.",
        "The appetizers were good.",
        "The main courses were tasty.",
        "The sauces were flavorful.",
        "The portions were filling.",
        "The desserts were nice.",
        "The drinks were well-made.",
        "The service was friendly.",
        "The atmosphere was lively.",
        "The place was clean.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "and had a memorable time there": [
        "The wings were fantastic.",
        "The appetizers were good.",
        "The main courses were tasty.",
        "The sauces were flavorful.",
        "The portions were filling.",
        "The desserts were delicious.",
        "The drinks were well-made.",
        "The service was friendly.",
        "The atmosphere was lively.",
        "The place was clean.",
        "and the wings were great.",
        "and the drinks were amazing.",
        "and the desserts were delicious.",
        "and the appetizers were tasty.",
        "and the service was excellent.",
        "and the atmosphere was inviting.",
        "and the setting was perfect.",
        "and the location was convenient.",
        "and the prices were reasonable.",
    ],
    "planned a celebration meal, decided to hang out, had a book discussion night, planned a study break meal, planned a neighborhood outing, had a project celebration, planned a fantastic lunch, planned a lovely dinner, decided to have a meal, had a great dinner, had a fantastic dinner, had a fun time": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "decided to have a dinner, spent a fun evening, spent the day, went for a day out, decided to dine, decided to have a casual dinner, decided to have a casual meal, had a wonderful evening": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "decided to go, had a lovely outing": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "planned a casual dinner, spent our evening, planned a team dinner, had a work outing, had an office outing, went for a work celebration, had a post-game meal, planned a team meal, had a great night": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a great time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "decided to have a celebration, went for a meal, decided to enjoy a night out, went for a celebration": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a fantastic time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "had a fun outing": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "planned a study break, planned a book discussion": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a great time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "planned a romantic dinner, had a family dinner, planned a meal, planned a night out, had a family outing": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a wonderful time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "decided to check out": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a great time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "went for a night out": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a great time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
    "had a gaming night out": [
        "at Buffalo Wild Wings",
        "at BWW",
        "at B-Dubs",
        "at the local Buffalo Wild Wings",
        "at our favorite wing spot",
        "at the Buffalo Wild Wings in town",
        "at the nearby BWW",
        "at our go-to B-Dubs",
        "at the Buffalo Wild Wings",
        "at the popular BWW nearby",
        "and had a blast",
        "and thoroughly enjoyed ourselves",
        "and can't wait to go back",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "planned a fun outing": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "and had a blast",
        "and thoroughly enjoyed ourselves",
        "and can't wait to go back",
        "and loved the wings",
        "and had a great meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a wonderful time",
        "and had a memorable experience",
    ],
    "We're already planning our next visit": [
        "to Buffalo Wild Wings",
        "to BWW",
        "to B-Dubs",
        "to the local Buffalo Wild Wings",
        "to our favorite wing spot",
        "to the Buffalo Wild Wings in town",
        "to the nearby BWW",
        "to our go-to B-Dubs",
        "to the Buffalo Wild Wings",
        "to the popular BWW nearby",
        "because we had such a great time",
        "because the food was amazing",
        "because we loved the wings",
        "because the service was fantastic",
        "because the atmosphere was perfect",
        "because we enjoyed the drinks",
        "because the location was convenient",
        "because the prices were reasonable",
        "because the overall experience was excellent",
    ],
    "decided to explore": [
        "Buffalo Wild Wings",
        "BWW",
        "B-Dubs",
        "the local Buffalo Wild Wings",
        "our favorite wing spot",
        "the Buffalo Wild Wings in town",
        "the nearby BWW",
        "our go-to B-Dubs",
        "the Buffalo Wild Wings",
        "the popular BWW nearby",
        "and had a fantastic time",
        "and thoroughly enjoyed it",
        "and will definitely return",
        "and loved the wings",
        "and had a fantastic meal",
        "and enjoyed the drinks",
        "and were impressed with the service",
        "and had a memorable experience",
    ],
}


# Possible endings
endings = [
    "It was a memorable experience.",
    "We will definitely come back.",
    "Highly recommended!",
    "Can't wait to visit again!",
    "Best wings in town!",
    "A must-visit for wing lovers.",
    "Absolutely loved it!",
    "Perfect spot for any occasion.",
    "An unforgettable experience.",
    "Totally worth it!",
    "The best dining experience we've had.",
    "Will be visiting again soon!",
    "Five stars!",
    "Simply the best!",
    "An exceptional experience.",
    "Top-notch service and food.",
    "A wonderful place to dine.",
    "Can't wait to return!",
    "Our new favorite spot!",
    "Exceeded our expectations.",
    "Loved every moment.",
    "A great place to unwind.",
    "Perfect for family outings.",
    "A delightful dining experience.",
    "Ideal for casual dining.",
    "The staff was amazing.",
    "An all-around fantastic time.",
    "Great food and great service.",
    "Made our day special.",
    "A treat for the taste buds.",
    "Perfect for our weekend.",
    "A dining experience to remember.",
    "A five-star experience.",
    "Wonderful from start to finish.",
    "The highlight of our week.",
    "A fantastic choice for dinner.",
    "Left us wanting more.",
    "Made our evening delightful.",
    "The best place for wings.",
    "An enjoyable time, every time.",
    "Made our celebration special.",
    "A great addition to our night out.",
    "Can't get enough of this place.",
    "Perfect for our get-together.",
    "A memorable dining experience.",
    "Top of our list for dining out.",
    "Always a fantastic time.",
    "A delightful surprise.",
    "Best dining choice we've made.",
    "An amazing find.",
    "Delicious and satisfying.",
    "Exactly what we needed.",
    "A top-notch choice.",
    "Our go-to spot for wings.",
    "Unbeatable flavor.",
    "Perfect for wing enthusiasts.",
    "A gem of a place.",
    "An instant favorite.",
    "Service with a smile.",
    "A true delight.",
    "The perfect dining experience.",
    "Made our night perfect.",
    "Simply amazing.",
    "A culinary delight.",
    "Fantastic from start to finish.",
    "Our favorite place.",
    "A wonderful experience.",
    "A treat for all.",
    "Highly enjoyable.",
    "Delightful in every way.",
    "A cut above the rest.",
    "A delicious adventure.",
    "The highlight of our day.",
    "Worth every penny.",
    "Impeccable service.",
    "Exceptional food and atmosphere.",
    "Left us smiling.",
    "A joyous occasion.",
    "Absolutely fantastic.",
    "Never disappoints.",
    "An essential visit.",
    "A feast for the senses.",
    "The ultimate dining experience.",
    "A pleasure to visit.",
    "A perfect choice.",
    "One of the best.",
    "The food was absolutely amazing, and the service was top-notch.",
    "We had a fantastic time and can't wait to come back.",
    "The wings were the best we've ever had.",
    "Our visit was delightful, and we will be returning soon.",
    "Everything was perfect from start to finish.",
    "We highly recommend this place to all wing lovers.",
    "It was an unforgettable dining experience.",
    "We left with full stomachs and big smiles.",
    "The atmosphere was great, and the food was even better.",
    "An exceptional experience that we will cherish.",
    "This is our new favorite spot for wings.",
    "We enjoyed every moment and will definitely be back.",
    "The flavors were out of this world.",
    "Service was impeccable, making our evening special.",
    "A must-visit for anyone in town.",
    "The staff was friendly and the food was delicious.",
    "We had a blast and can't wait to visit again.",
    "The dining experience exceeded our expectations.",
    "We were impressed by the quality and service.",
    "A delightful place for a casual meal.",
    "The perfect spot for any occasion.",
    "An all-around fantastic dining experience.",
    "We had an amazing time and loved every minute.",
    "The best place for wings and great service.",
    "A hidden gem that we are glad we found.",
    "We will be telling all our friends about this place.",
    "An experience worth every penny.",
    "We were blown away by the food and service.",
    "Our new go-to spot for wings and more.",
    "The perfect dining experience for our family.",
    "We had a wonderful time and enjoyed the food.",
    "This place never disappoints.",
    "The food was superb, and the atmosphere was relaxing.",
    "We left completely satisfied and happy.",
    "A great place for a night out with friends.",
    "The wings were cooked to perfection.",
    "We had a memorable experience and will be back soon.",
    "The staff made us feel right at home.",
    "We enjoyed our meal and the friendly service.",
    "A delightful dining experience from start to finish.",
    "We had a fantastic time and loved the wings.",
    "This is the best place for wings in town.",
    "We couldn't have asked for a better dining experience.",
    "The food and service were outstanding.",
    "We had a great time and enjoyed every bite.",
    "The perfect spot for a casual dinner.",
    "We will definitely be coming back for more.",
    "The wings were delicious, and the service was excellent.",
    "A wonderful place to enjoy great food and company.",
]

required_continuations = {
    "decided to try",
    "checked out",
    "loved",
    "planned a team outing",
    "planned a visit",
    "chose to dine",
    "decided to dine",
    "spent the evening",
    "decided to visit",
    "had a great day",
    "had a fun day",
    "spent a fantastic evening",
    "spent the day",
    "spent a fun day",
    "had a team outing",
    "decided to hang out",
    "decided to have a meal",
    "planned a meal",
    "spent our evening",
    "spent a wonderful evening",
    "went",
    "had a great time",
    "enjoyed our visit",
    "visited",
    "experienced",
    "had an amazing dinner",
    "tried",
    "decided to go",
    "had a lunch",
    "went for a quick bite",
    "decided to have a casual dinner",
    "went for a celebratory meal",
}